import { ChevronDown, Cpu, Gauge } from "lucide-react";
import { useState } from "react";

import { SectionCard } from "@/components/common/stat-card";
import { Tag } from "@/components/common/status-badge";
import { Button } from "@/components/ui/button";
import { providerLabel } from "@/lib/analysis/analysis";

type Summary = Record<string, unknown>;

const METRIC_LABELS: Record<string, string> = {
  videoDurationSeconds: "Film duration (s)",
  detectorBackend: "Detector",
  detectorPrecision: "Precision",
  device: "Compute device",
  batchSize: "Inference batch size",
  detectEveryNthFrame: "Detection cadence (every N frames)",
  reidIntervalSeconds: "Re-ID cadence (s)",
  framesDecoded: "Frames decoded",
  framesDetected: "Frames detected",
  framesTrackedBetween: "Frames motion-tracked",
  framesSkippedDeadTime: "Frames skipped (dead time)",
  detectionsDroppedOffCourt: "Detections dropped (off-court)",
  reidEvaluations: "Re-ID evaluations",
  analyzedSeconds: "Film analysed (s)",
  analyzedCoveragePercent: "Film coverage (%)",
  framesAnalyzed: "Frames analysed",
  analysisFps: "Analysis FPS",
  detectionResolution: "Detection width (px)",
  detections: "Person detections",
  detectionsPerFrame: "Detections / frame",
  tracks: "Tracks returned",
  tracksCreated: "Tracks created",
  framesWithTarget: "Frames with target",
  targetTrackingCoverage: "Tracking coverage",
  targetVisibleSeconds: "Target visible (s)",
  targetTrackChanges: "Identity switches",
  lowConfidenceIntervals: "Low-confidence intervals",
  confirmationsSupplied: "Confirmations supplied",
  confirmationsMatched: "Confirmations matched",
  referenceImagesUsed: "Reference images used",
  confirmedReferencesUsed: "Confirmed references used",
  meanIdentityConfidence: "Mean identity confidence",
  ballDetectedFrames: "Frames with ball",
  candidateClips: "Candidate clips",
  analysisDurationSeconds: "Processing time (s)",
};

function formatValue(key: string, value: unknown): string {
  if (typeof value === "number") {
    if (key === "targetTrackingCoverage") return `${Math.round(value * 100)}%`;
    return Number.isInteger(value) ? String(value) : value.toFixed(2);
  }
  return String(value ?? "—");
}

/**
 * Admin/debug attribution for one analysis run: which service produced it, the
 * model versions behind it, real inference metrics, and a few annotated frames.
 * Never shown to athletes as analysis "insight" — it is engineering detail.
 */
export function AnalysisDiagnostics({
  summary,
  provider,
  isDemo,
  modelVersion,
}: {
  summary: Summary | null | undefined;
  provider: string;
  isDemo: boolean;
  modelVersion: string | null;
}) {
  const [open, setOpen] = useState(false);
  const attribution = providerLabel({ provider, isDemo });
  const metrics = (summary?.["metrics"] ?? null) as Record<string, unknown> | null;
  const versions = (summary?.["model_versions"] ?? null) as Record<string, unknown> | null;
  const frames = (summary?.["debug_frames"] ?? []) as {
    timestamp: number;
    imageBase64?: string | null;
    imageUrl?: string | null;
    boxes?: { trackId: string; identityConfidence: number }[];
  }[];

  const entries = metrics
    ? Object.entries(METRIC_LABELS).filter(([key]) => metrics[key] !== undefined)
    : [];

  return (
    <SectionCard
      title="Analysis diagnostics"
      description="Provider attribution, model versions and measured tracking performance."
      actions={
        <div className="flex flex-wrap items-center gap-1.5">
          <span
            className={
              attribution.isDemo
                ? "label-caps inline-flex items-center gap-1.5 rounded-full border border-warning/40 bg-warning/15 px-2.5 py-0.5 text-[11px] text-warning"
                : "label-caps inline-flex items-center gap-1.5 rounded-full border border-success/40 bg-success/15 px-2.5 py-0.5 text-[11px] text-success"
            }
          >
            <Cpu className="size-3" />
            {attribution.label}
          </span>
          {modelVersion ? <Tag>{modelVersion}</Tag> : null}
        </div>
      }
    >
      {attribution.isDemo ? (
        <p className="mb-3 text-sm text-muted-foreground">
          These results were generated by the development mock provider, not by real computer
          vision. Nothing here reflects the actual film.
        </p>
      ) : null}

      {entries.length === 0 ? (
        <p className="text-sm text-muted-foreground">
          No metrics were reported for this run.
        </p>
      ) : (
        <dl className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
          {entries.map(([key, label]) => (
            <div
              key={key}
              className="rounded-lg border border-border bg-surface-2 px-3 py-2"
            >
              <dt className="label-caps text-[10px] text-muted-foreground">{label}</dt>
              <dd className="text-sm font-semibold tabular-nums">
                {formatValue(key, metrics?.[key])}
              </dd>
            </div>
          ))}
        </dl>
      )}

      {versions || frames.length > 0 ? (
        <div className="mt-3">
          <Button variant="outline" size="sm" onClick={() => setOpen((value) => !value)}>
            <Gauge className="size-4" />
            {open ? "Hide" : "Show"} model versions &amp; sample frames
            <ChevronDown className={open ? "size-4 rotate-180" : "size-4"} />
          </Button>
          {open ? (
            <div className="mt-3 space-y-3">
              {versions ? (
                <ul className="grid gap-1 text-xs text-muted-foreground">
                  {Object.entries(versions).map(([key, value]) => (
                    <li key={key} className="flex gap-2">
                      <span className="label-caps text-[10px]">{key}</span>
                      <span className="font-mono">{String(value)}</span>
                    </li>
                  ))}
                </ul>
              ) : null}
              {frames.length > 0 ? (
                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                  {frames.map((frame) => (
                    <figure key={frame.timestamp} className="space-y-1">
                      <img
                        src={frame.imageBase64 ?? frame.imageUrl ?? ""}
                        alt={`Tracked player at ${frame.timestamp} seconds`}
                        loading="lazy"
                        className="w-full rounded-lg border border-border"
                      />
                      <figcaption className="text-[11px] tabular-nums text-muted-foreground">
                        {frame.timestamp}s
                        {frame.boxes?.[0]
                          ? ` · ${frame.boxes[0].trackId} · ${frame.boxes[0].identityConfidence}`
                          : ""}
                      </figcaption>
                    </figure>
                  ))}
                </div>
              ) : null}
            </div>
          ) : null}
        </div>
      ) : null}
    </SectionCard>
  );
}
