/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevelopmentRouteImport } from './routes/_authenticated/development'
import { Route as AuthenticatedFilmRoomRouteImport } from './routes/_authenticated/film-room'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedGamesGameIdRouteImport } from './routes/_authenticated/games.$gameId'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players.$playerId'
import { Route as OauthGoogleDriveReturnRouteImport } from './routes/oauth/google-drive.return'
import { Route as ApiPublicDriveStreamAssetIdRouteImport } from './routes/api/public/drive-stream.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevelopmentRoute =
  AuthenticatedDevelopmentRouteImport.update({
    id: '/development',
    path: '/development',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilmRoomRoute = AuthenticatedFilmRoomRouteImport.update({
  id: '/film-room',
  path: '/film-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesGameIdRoute =
  AuthenticatedGamesGameIdRouteImport.update({
    id: '/$gameId',
    path: '/$gameId',
    getParentRoute: () => AuthenticatedGamesRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/$playerId',
    path: '/$playerId',
    getParentRoute: () => AuthenticatedPlayersRoute,
  } as any)
const OauthGoogleDriveReturnRoute = OauthGoogleDriveReturnRouteImport.update({
  id: '/oauth/google-drive/return',
  path: '/oauth/google-drive/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveStreamAssetIdRoute =
  ApiPublicDriveStreamAssetIdRouteImport.update({
    id: '/api/public/drive-stream/$assetId',
    path: '/api/public/drive-stream/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development': typeof AuthenticatedDevelopmentRoute
  '/film-room': typeof AuthenticatedFilmRoomRoute
  '/games': typeof AuthenticatedGamesRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/players': typeof AuthenticatedPlayersRouteWithChildren
  '/reels': typeof AuthenticatedReelsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/api/public/drive-stream/$assetId': typeof ApiPublicDriveStreamAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development': typeof AuthenticatedDevelopmentRoute
  '/film-room': typeof AuthenticatedFilmRoomRoute
  '/games': typeof AuthenticatedGamesRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/players': typeof AuthenticatedPlayersRouteWithChildren
  '/reels': typeof AuthenticatedReelsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/api/public/drive-stream/$assetId': typeof ApiPublicDriveStreamAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/development': typeof AuthenticatedDevelopmentRoute
  '/_authenticated/film-room': typeof AuthenticatedFilmRoomRoute
  '/_authenticated/games': typeof AuthenticatedGamesRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRouteWithChildren
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/api/public/drive-stream/$assetId': typeof ApiPublicDriveStreamAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/development'
    | '/film-room'
    | '/games'
    | '/onboarding'
    | '/players'
    | '/reels'
    | '/settings'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/oauth/google-drive/return'
    | '/api/public/drive-stream/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/development'
    | '/film-room'
    | '/games'
    | '/onboarding'
    | '/players'
    | '/reels'
    | '/settings'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/oauth/google-drive/return'
    | '/api/public/drive-stream/$assetId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/development'
    | '/_authenticated/film-room'
    | '/_authenticated/games'
    | '/_authenticated/onboarding'
    | '/_authenticated/players'
    | '/_authenticated/reels'
    | '/_authenticated/settings'
    | '/_authenticated/games/$gameId'
    | '/_authenticated/players/$playerId'
    | '/oauth/google-drive/return'
    | '/api/public/drive-stream/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OauthGoogleDriveReturnRoute: typeof OauthGoogleDriveReturnRoute
  ApiPublicDriveStreamAssetIdRoute: typeof ApiPublicDriveStreamAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/development': {
      id: '/_authenticated/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof AuthenticatedDevelopmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/film-room': {
      id: '/_authenticated/film-room'
      path: '/film-room'
      fullPath: '/film-room'
      preLoaderRoute: typeof AuthenticatedFilmRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/$gameId': {
      id: '/_authenticated/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthenticatedGamesGameIdRouteImport
      parentRoute: typeof AuthenticatedGamesRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedPlayersRoute
    }
    '/oauth/google-drive/return': {
      id: '/oauth/google-drive/return'
      path: '/oauth/google-drive/return'
      fullPath: '/oauth/google-drive/return'
      preLoaderRoute: typeof OauthGoogleDriveReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-stream/$assetId': {
      id: '/api/public/drive-stream/$assetId'
      path: '/api/public/drive-stream/$assetId'
      fullPath: '/api/public/drive-stream/$assetId'
      preLoaderRoute: typeof ApiPublicDriveStreamAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedGamesRouteChildren {
  AuthenticatedGamesGameIdRoute: typeof AuthenticatedGamesGameIdRoute
}

const AuthenticatedGamesRouteChildren: AuthenticatedGamesRouteChildren = {
  AuthenticatedGamesGameIdRoute: AuthenticatedGamesGameIdRoute,
}

const AuthenticatedGamesRouteWithChildren =
  AuthenticatedGamesRoute._addFileChildren(AuthenticatedGamesRouteChildren)

interface AuthenticatedPlayersRouteChildren {
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
}

const AuthenticatedPlayersRouteChildren: AuthenticatedPlayersRouteChildren = {
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
}

const AuthenticatedPlayersRouteWithChildren =
  AuthenticatedPlayersRoute._addFileChildren(AuthenticatedPlayersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevelopmentRoute: typeof AuthenticatedDevelopmentRoute
  AuthenticatedFilmRoomRoute: typeof AuthenticatedFilmRoomRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRouteWithChildren
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevelopmentRoute: AuthenticatedDevelopmentRoute,
  AuthenticatedFilmRoomRoute: AuthenticatedFilmRoomRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlayersRoute: AuthenticatedPlayersRouteWithChildren,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OauthGoogleDriveReturnRoute: OauthGoogleDriveReturnRoute,
  ApiPublicDriveStreamAssetIdRoute: ApiPublicDriveStreamAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
