/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevelopmentRouteImport } from './routes/_authenticated/development'
import { Route as AuthenticatedFilmRoomRouteImport } from './routes/_authenticated/film-room'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAnalysisJobIdRouteImport } from './routes/_authenticated/analysis.$jobId'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games.index'
import { Route as AuthenticatedGamesGameIdRouteImport } from './routes/_authenticated/games.$gameId'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players.index'
import { Route as AuthenticatedPlayersPlayerIdRouteImport } from './routes/_authenticated/players.$playerId'
import { Route as ApiPublicCvProbeRouteImport } from './routes/api/public/cv-probe'
import { Route as OauthGoogleDriveReturnRouteImport } from './routes/oauth/google-drive.return'
import { Route as ApiPublicDriveStreamAssetIdRouteImport } from './routes/api/public/drive-stream.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevelopmentRoute =
  AuthenticatedDevelopmentRouteImport.update({
    id: '/development',
    path: '/development',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilmRoomRoute = AuthenticatedFilmRoomRouteImport.update({
  id: '/film-room',
  path: '/film-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisJobIdRoute =
  AuthenticatedAnalysisJobIdRouteImport.update({
    id: '/analysis/$jobId',
    path: '/analysis/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesGameIdRoute =
  AuthenticatedGamesGameIdRouteImport.update({
    id: '/games/$gameId',
    path: '/games/$gameId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersPlayerIdRoute =
  AuthenticatedPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCvProbeRoute = ApiPublicCvProbeRouteImport.update({
  id: '/api/public/cv-probe',
  path: '/api/public/cv-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleDriveReturnRoute = OauthGoogleDriveReturnRouteImport.update({
  id: '/oauth/google-drive/return',
  path: '/oauth/google-drive/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDriveStreamAssetIdRoute =
  ApiPublicDriveStreamAssetIdRouteImport.update({
    id: '/api/public/drive-stream/$assetId',
    path: '/api/public/drive-stream/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development': typeof AuthenticatedDevelopmentRoute
  '/film-room': typeof AuthenticatedFilmRoomRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/analysis/$jobId': typeof AuthenticatedAnalysisJobIdRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/api/public/cv-probe': typeof ApiPublicCvProbeRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/players/': typeof AuthenticatedPlayersIndexRoute
  '/api/public/drive-stream/$assetId': typeof ApiPublicDriveStreamAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/development': typeof AuthenticatedDevelopmentRoute
  '/film-room': typeof AuthenticatedFilmRoomRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/analysis/$jobId': typeof AuthenticatedAnalysisJobIdRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/api/public/cv-probe': typeof ApiPublicCvProbeRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/api/public/drive-stream/$assetId': typeof ApiPublicDriveStreamAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/development': typeof AuthenticatedDevelopmentRoute
  '/_authenticated/film-room': typeof AuthenticatedFilmRoomRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/analysis/$jobId': typeof AuthenticatedAnalysisJobIdRoute
  '/_authenticated/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/_authenticated/players/$playerId': typeof AuthenticatedPlayersPlayerIdRoute
  '/api/public/cv-probe': typeof ApiPublicCvProbeRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/api/public/drive-stream/$assetId': typeof ApiPublicDriveStreamAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/development'
    | '/film-room'
    | '/onboarding'
    | '/reels'
    | '/settings'
    | '/analysis/$jobId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/api/public/cv-probe'
    | '/oauth/google-drive/return'
    | '/games/'
    | '/players/'
    | '/api/public/drive-stream/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/development'
    | '/film-room'
    | '/onboarding'
    | '/reels'
    | '/settings'
    | '/analysis/$jobId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/api/public/cv-probe'
    | '/oauth/google-drive/return'
    | '/games'
    | '/players'
    | '/api/public/drive-stream/$assetId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/development'
    | '/_authenticated/film-room'
    | '/_authenticated/onboarding'
    | '/_authenticated/reels'
    | '/_authenticated/settings'
    | '/_authenticated/analysis/$jobId'
    | '/_authenticated/games/$gameId'
    | '/_authenticated/players/$playerId'
    | '/api/public/cv-probe'
    | '/oauth/google-drive/return'
    | '/_authenticated/games/'
    | '/_authenticated/players/'
    | '/api/public/drive-stream/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCvProbeRoute: typeof ApiPublicCvProbeRoute
  OauthGoogleDriveReturnRoute: typeof OauthGoogleDriveReturnRoute
  ApiPublicDriveStreamAssetIdRoute: typeof ApiPublicDriveStreamAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/development': {
      id: '/_authenticated/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof AuthenticatedDevelopmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/film-room': {
      id: '/_authenticated/film-room'
      path: '/film-room'
      fullPath: '/film-room'
      preLoaderRoute: typeof AuthenticatedFilmRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis/$jobId': {
      id: '/_authenticated/analysis/$jobId'
      path: '/analysis/$jobId'
      fullPath: '/analysis/$jobId'
      preLoaderRoute: typeof AuthenticatedAnalysisJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/$gameId': {
      id: '/_authenticated/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthenticatedGamesGameIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/$playerId': {
      id: '/_authenticated/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cv-probe': {
      id: '/api/public/cv-probe'
      path: '/api/public/cv-probe'
      fullPath: '/api/public/cv-probe'
      preLoaderRoute: typeof ApiPublicCvProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-drive/return': {
      id: '/oauth/google-drive/return'
      path: '/oauth/google-drive/return'
      fullPath: '/oauth/google-drive/return'
      preLoaderRoute: typeof OauthGoogleDriveReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/drive-stream/$assetId': {
      id: '/api/public/drive-stream/$assetId'
      path: '/api/public/drive-stream/$assetId'
      fullPath: '/api/public/drive-stream/$assetId'
      preLoaderRoute: typeof ApiPublicDriveStreamAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevelopmentRoute: typeof AuthenticatedDevelopmentRoute
  AuthenticatedFilmRoomRoute: typeof AuthenticatedFilmRoomRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAnalysisJobIdRoute: typeof AuthenticatedAnalysisJobIdRoute
  AuthenticatedGamesGameIdRoute: typeof AuthenticatedGamesGameIdRoute
  AuthenticatedPlayersPlayerIdRoute: typeof AuthenticatedPlayersPlayerIdRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevelopmentRoute: AuthenticatedDevelopmentRoute,
  AuthenticatedFilmRoomRoute: AuthenticatedFilmRoomRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAnalysisJobIdRoute: AuthenticatedAnalysisJobIdRoute,
  AuthenticatedGamesGameIdRoute: AuthenticatedGamesGameIdRoute,
  AuthenticatedPlayersPlayerIdRoute: AuthenticatedPlayersPlayerIdRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCvProbeRoute: ApiPublicCvProbeRoute,
  OauthGoogleDriveReturnRoute: OauthGoogleDriveReturnRoute,
  ApiPublicDriveStreamAssetIdRoute: ApiPublicDriveStreamAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
